/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import koneksi.koneksi;

/**
 *
 * @author subki
 */
public class offerform extends javax.swing.JDialog {

    Connection conec;
    public String submit;
    public offerform(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conec = new koneksi().connection();
        //bahasa();
        taheader.setLineWrap(true);
        taheader.setWrapStyleWord(true);
        tafooter.setLineWrap(true);
        tafooter.setWrapStyleWord(true);
        setLocationRelativeTo(this);
        
        this.setTitle("Offer Letters");
        this.setIconImage(new ImageIcon(getClass().getResource("/image/ssm.png")).getImage());
        
        
        Calendar kalender = new GregorianCalendar();
        int thn = kalender.get(Calendar.YEAR);
        int bln = kalender.get(Calendar.MONTH)+1;
        int tgl = kalender.get(Calendar.DATE);
        txtDate.setText(String.valueOf(thn)+"-"+String.valueOf(bln)+"-"+String.valueOf(tgl));
        btnCari.setIcon(new ImageIcon(getClass().getResource("/image/search110.png")));
        jButton2.setIcon(new ImageIcon(getClass().getResource("/image/letterx.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtbahasa = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tfnomor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbcur = new javax.swing.JComboBox();
        tfcur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbIndo = new javax.swing.JRadioButton();
        rbEng = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        taheader = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tafooter = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfsucject = new javax.swing.JTextField();
        tfref = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        togel1 = new javax.swing.JToggleButton();
        togel2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        tfdiskon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfppn = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfcust = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcust = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        txtbahasa.setText("jLabel3");

        btnPrint.setText("Save & Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PREPARATION OFFER LETTER");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PT. SUMBER SURYA MANDIRI");

        tfnomor.setEnabled(false);

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDate.setText("dd-MM-yyyy");

        jLabel5.setText("Currency");

        cbcur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".:: Pilih Currency ::.", "IDR", "USD", "Other" }));
        cbcur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcurActionPerformed(evt);
            }
        });

        tfcur.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setText("Enter Currency");

        jLabel7.setText("Language");

        buttonGroup1.add(rbIndo);
        rbIndo.setText("Indonseian");
        rbIndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIndoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEng);
        rbEng.setText("English");
        rbEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEngActionPerformed(evt);
            }
        });

        taheader.setColumns(20);
        taheader.setRows(5);
        taheader.setEnabled(false);
        jScrollPane1.setViewportView(taheader);

        tafooter.setColumns(20);
        tafooter.setRows(5);
        tafooter.setEnabled(false);
        jScrollPane2.setViewportView(tafooter);

        jLabel8.setText("Header :");

        jLabel9.setText("Footer :");

        btnSubmit.setText("Save");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel10.setText("Subject");

        jLabel11.setText("Ref.");

        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        togel1.setText("Edit");
        togel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togel1ActionPerformed(evt);
            }
        });

        togel2.setText("Edit");
        togel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togel2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Discount");

        jLabel4.setText("%");

        jLabel12.setText("PPN");

        jLabel13.setText("%");

        tfcust.setEnabled(false);

        jLabel15.setText("Customer");

        jLabel14.setText("No");

        jButton1.setText("Detail Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(togel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(togel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfcust)
                                    .addComponent(tfnomor, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcust)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbcur, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfcur, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbIndo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbEng)))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfref, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(tfsucject))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfppn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnSubmit)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(txtDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfcust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcust)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbcur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfsucject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(tfref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rbIndo)
                            .addComponent(rbEng)
                            .addComponent(jLabel3)
                            .addComponent(tfdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(tfppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(togel1)
                            .addComponent(togel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCari)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbIndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIndoActionPerformed
        System.out.println("data no : "+tfnomor.getText());
        if("".equals(tfnomor.getText())){
            JOptionPane.showMessageDialog(null, "Quo. Number tidak boleh kosong");
            buttonGroup1.clearSelection();
        }else{
            bahasa();
        }
        txtbahasa.setText("Indonesia");
    }//GEN-LAST:event_rbIndoActionPerformed

    private void rbEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEngActionPerformed
        System.out.println("data no : "+tfnomor.getText());
        if("".equals(tfnomor.getText())){
            JOptionPane.showMessageDialog(null, "Quo. Number tidak boleh kosong");
            buttonGroup1.clearSelection();
        }else{
            bahasa();
        }
        txtbahasa.setText("English");
    }//GEN-LAST:event_rbEngActionPerformed

    private void cbcurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcurActionPerformed
        if(cbcur.getSelectedIndex() == 0){
            tfcur.setEnabled(true);
            tfcur.setText("");
        }else if(cbcur.getSelectedIndex() == 1){
            tfcur.setEnabled(false);
            tfcur.setText(cbcur.getSelectedItem().toString());
        }else if(cbcur.getSelectedIndex() == 2){
            tfcur.setEnabled(false);
            tfcur.setText(cbcur.getSelectedItem().toString());
        }else if(cbcur.getSelectedIndex() == 3){
            tfcur.setEnabled(true);
            tfcur.setText("");
        }
    }//GEN-LAST:event_cbcurActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        DetailCustomer dt = new DetailCustomer(null, true);
        dt.setVisible(true);
        CustomerOBJ o = dt.getData();
        if(o != null){
            tfcust.setText(o.getId());
            txtcust.setText(o.getNama());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void togel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togel1ActionPerformed
        if(togel1.isSelected()){
            taheader.setEnabled(true);
            togel1.setText("Ok");
        }else{
            taheader.setEnabled(false);
            togel1.setText("Edit");
        }
    }//GEN-LAST:event_togel1ActionPerformed

    private void togel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togel2ActionPerformed
        if(togel2.isSelected()){
            tafooter.setEnabled(true);
            togel2.setText("Ok");
        }else{
            tafooter.setEnabled(false);
            togel2.setText("Edit");
        }
    }//GEN-LAST:event_togel2ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(btnSubmit.getText().equals("Save")){
            if(!tfnomor.getText().equals("")){
                save();
                System.out.println("Save");
            }else{
                JOptionPane.showMessageDialog(null, "Quo. Number tidak boleh kosong");
            }
        }
        if(btnSubmit.getText().equals("Update")){
            if(!tfnomor.getText().equals("")){
                update();
            }else{
                JOptionPane.showMessageDialog(null, "Quo. Number tidak boleh kosong");
            }
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if(btnPrint.getText().equals("Save & Print")){
            if(!tfnomor.getText().equals("")){
                save();
            }else{
                JOptionPane.showMessageDialog(null, "Quo. Number tidak boleh kosong");
            }
        }
        if(btnPrint.getText().equals("Update & Print")){
            if(!tfnomor.getText().equals("")){
                update();
            }else{
                JOptionPane.showMessageDialog(null, "Quo. Number tidak boleh kosong");
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        offerformdetail fr = new offerformdetail(null, true);
        fr.submit = "save";
        fr.getBtnsubmit().setIcon(new ImageIcon(getClass().getResource("/image/zoomin.png")));
        fr.numbering(tfnomor.getText());
        fr.createtable(tfnomor.getText());
        fr.getTfnomor().setText(tfnomor.getText());
        fr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(offerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(offerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(offerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(offerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                offerform dialog = new offerform(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbcur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rbEng;
    private javax.swing.JRadioButton rbIndo;
    private javax.swing.JTextArea tafooter;
    private javax.swing.JTextArea taheader;
    private javax.swing.JTextField tfcur;
    private javax.swing.JTextField tfcust;
    private javax.swing.JTextField tfdiskon;
    private javax.swing.JTextField tfnomor;
    private javax.swing.JTextField tfppn;
    private javax.swing.JTextField tfref;
    private javax.swing.JTextField tfsucject;
    private javax.swing.JToggleButton togel1;
    private javax.swing.JToggleButton togel2;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtbahasa;
    private javax.swing.JLabel txtcust;
    // End of variables declaration//GEN-END:variables

    public JTextField getTfcur() {
        return tfcur;
    }

    public JTextField getTfnomor() {
        return tfnomor;
    }

    public JTextField getTfref() {
        return tfref;
    }

    public JTextField getTfsucject() {
        return tfsucject;
    }

    public JComboBox getCbcur() {
        return cbcur;
    }

    public JButton getBtnCari() {
        return btnCari;
    }

    public JButton getBtnPrint() {
        return btnPrint;
    }

    public JButton getBtnSubmit() {
        return btnSubmit;
    }
    
    public void bahasa(){
        String header = null, footer = null;
        HashMap<String,String> arr = new HashMap<String, String>();
        arr = cari(tfcust.getText());
        if((rbIndo.isSelected()==true)){
            header = "Kepada    : "+arr.get("nama") +" \n"
                    + ""+arr.get("alamat") +" \n"
                    + "Telepon  : "+arr.get("telepon") +" \n"
                    + "No Fax   : "+arr.get("fax") +" \n"
                    + "Up       : "+arr.get("pic") +"\n"
                    + "Subyek   : "+tfsucject.getText()+" \n"
                    + "\n"
                    + "\n"
                    + "Re : "+tfref.getText()+"\n"
                    + "\n"
                    + "Dengan Hormat, \n"
                    + "Kami mengucapkan terima kasih atas permintaannya. Berikut ini kami kirimkan PENAWARAN untuk proyek ini";
            footer ="Tempo Pembayaran :\n"
                    + "40% Uang muka ,  60% sebelum pengiriman\n"
                    + "\n"
                    + "Ketentuan Harga :\n"
                    + "Harga nett, tidak termasuk Packing dan PPN. \n"
                    + "Proses pengerjaan di Plant Balaraja.\n"
                    + "Tidak termasuk desain dan pengkabelan.\n"
                    + "Tidak termasuk installasi dan pemasangan.\n"
                    + "\n"
                    + "Waktu Pengiriman :\n"
                    + "Perkiraan waktu pengiriman berkisar dalam kurun waktu 4 bulan, setelah menerima Formal Order dan Uang Muka, dan setelah menerima skema.\n"
                    + "\n"
                    + "Validasi :\n"
                    + "Penawaran ini valid selama 30 hari terhitung sejak penawaran ini dikeluarkan.\n"
                    + "\n"
                    + "Kami berharap penawaran kami sesuai dengan harapan anda untuk informasi lebih lanjut, harap tidak segan untuk menghubungi kami.\n"
                    + "\n"
                    + "\n"
                    + "Hormat Kami,\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "(Seyo Sutjiono)  (Edy Mulawal)\n"
                    + "Sales Manager    : Budi Hartono (082289342)\n"
                    + "Contact Person   : Surya (8349342930)";
        }else if (rbEng.isSelected()==true){
            header = "To    : "+arr.get("nama") +" \n"
                    + ""+arr.get("alamat") +" \n"
                    + "Phone    : "+arr.get("telepon") +" \n"
                    + "Faximile : "+arr.get("fax") +" \n"
                    + "Attention: "+arr.get("pic") +"\n"
                    + "Subject  : "+tfsucject.getText()+" \n"
                    + "\n"
                    + "\n"
                    + "Re : "+tfref.getText()+"\n"
                    + "\n"
                    + "Dear Sir, \n"
                    + "We thank you for the enquiry, we are please to submit our OFFER for this project.";
            footer ="Payment Term :\n"
                    + "40% Downpayment ,  60% before delivery\n"
                    + "\n"
                    + "Price Condition\n"
                    + "Price is Nett,exluding Wooden packing, excluding VAT. \n"
                    + "Ex-Work Factory Balaraja.\n"
                    + "Secondary Design and cable schedule are excluded.\n"
                    + "Excluding Installation & Commissioning.\n"
                    + "\n"
                    + "Delivery Time :\n"
                    + "Estimated delivery time shall be within 4 mounth, after receipt of formal order and down payment, and after receipt of drawing.\n"
                    + "\n"
                    + "Validity :\n"
                    + "This quotation is valid for 30 days from the date of this quotation.\n"
                    + "\n"
                    + "We sincerely hope that our quotation is in accordance with your expectation and should you have any further queries, please don’t hesitate to contact us.\n"
                    + "\n"
                    + "\n"
                    + "Your Faithfully,\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "(Seyo Sutjiono)  (Edy Mulawal)\n"
                    + "Sales Manager    : Budi Hartono (082289342)\n"
                    + "Contact Person   : Surya (8349342930)";
        }
        
        taheader.setText(header);
        tafooter.setText(footer);
    }

    private HashMap<String, String> cari(String cust) {
        System.out.println("Customer : "+cust);
        String sql = "select * from customer where id=?";
        HashMap<String, String> data = new HashMap<String, String>();
        try {
            PreparedStatement ps = conec.prepareStatement(sql);
            ps.setString(1, cust);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                data.put("nama", rs.getString("nama"));
                data.put("alamat", rs.getString("alamat"));
                data.put("telepon", rs.getString("telepon"));
                data.put("fax", rs.getString("fax"));
                data.put("pic", rs.getString("pic1")+" / "+rs.getString("pic2"));
                
                System.out.println(data);
                return data;
            }
        } catch (SQLException ex) {
            Logger.getLogger(offerform.class.getName()).log(Level.SEVERE, null, ex);
        }
        return data;
    }

    private void save() {
        String nomor = tfnomor.getText();
        String curr = tfcur.getText();
        String bhsa = txtbahasa.getText();
        String tgl = txtDate.getText();
        String sbjk = tfsucject.getText();
        String ref = tfref.getText();
        String diskon = tfdiskon.getText();
        String ppn = tfppn.getText();
        String cust = tfcust.getText();
        String header = taheader.getText();
        String footer = tafooter.getText();
        String sql_cari="Select * from offer where offer_no=?";
        String sql = "insert into offer ("
                + "offer_no, "
                + "currency, "
                + "lang, "
                + "tgl, "
                + "subjek, "
                + "refer, "
                + "discount, "
                + "ppn, "
                + "customer, "
                + "header, "
                + "footer)"
                + "values (?,?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement pr = conec.prepareStatement(sql_cari);
            pr.setString(1, nomor);
            ResultSet rs = pr.executeQuery();
            if(rs.next()){
                int opt = JOptionPane.showConfirmDialog(null,
                        "Data sudah ada, \n Update?", "Duplikat Offer", JOptionPane.YES_NO_OPTION);
                if(opt == JOptionPane.YES_OPTION){
                    update();
                }
            }else{
                PreparedStatement ps = conec.prepareStatement(sql);
                ps.setString(1, nomor);
                ps.setString(2, curr);
                ps.setString(3, bhsa);
                ps.setString(4, tgl);
                ps.setString(5, sbjk);
                ps.setString(6, ref);
                ps.setString(7, diskon);
                ps.setString(8, ppn);
                ps.setString(9, cust);
                ps.setString(10, header);
                ps.setString(11, footer);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil di tambahkan");
                update_faktur();
                this.dispose();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(offerform.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    public void update(){
        String nomor = tfnomor.getText();
        String curr = tfcur.getText();
        String bhsa = txtbahasa.getText();
        String tgl = txtDate.getText();
        String sbjk = tfsucject.getText();
        String ref = tfref.getText();
        String diskon = tfdiskon.getText();
        String ppn = tfppn.getText();
        String cust = tfcust.getText();
        String header = taheader.getText();
        String footer = tafooter.getText();
        String sql_cari="Select * from offer where offer_no=?";
        String sql = "update offer set "
                + "currency=?, "
                + "lang=?, "
                + "tgl=?, "
                + "subjek=?, "
                + "refer=?, "
                + "discount=?, "
                + "ppn=?, "
                + "customer=?, "
                + "header=?, "
                + "footer=? where offer_no=?";
        try {
            PreparedStatement pr = conec.prepareStatement(sql_cari);
            pr.setString(1, nomor);
            ResultSet rs = pr.executeQuery();
            if(rs.next()){
                PreparedStatement ps = conec.prepareStatement(sql);
                ps.setString(1, curr);
                ps.setString(2, bhsa);
                ps.setString(3, tgl);
                ps.setString(4, sbjk);
                ps.setString(5, ref);
                ps.setString(6, diskon);
                ps.setString(7, ppn);
                ps.setString(8, cust);
                ps.setString(9, header);
                ps.setString(10, footer);
                ps.setString(11, nomor);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil di ubah");
                this.dispose();
            }else{
                int opt = JOptionPane.showConfirmDialog(null,
                        "Data belum ada, \n Simpan baru?", "Data unknown", JOptionPane.YES_NO_OPTION);
                if(opt == JOptionPane.YES_OPTION){
                    save();
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(offerform.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    void search_header(String no, String nama) {
        String sql = "select * from offer where offer_no=?";
        try {
            PreparedStatement ps = conec.prepareStatement(sql);
            ps.setString(1, no);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                tfnomor.setText(rs.getString("offer_no"));
//                txtnomor.setText(nama);
                String curr = rs.getString("currency");
                if(curr != "IDR" || curr != "USD"){
                    cbcur.setSelectedIndex(3);
                }else{
                    cbcur.setSelectedItem(curr);
                }
                tfcur.setText(curr);
                String lang = rs.getString("lang");
                if(lang == "Indonesia"){
                    rbIndo.setSelected(true);
                }
                if(lang == "English"){
                    rbEng.setSelected(true);
                }
                tfsucject.setText(rs.getString("subjek"));
                tfref.setText(rs.getString("refer"));
                tfdiskon.setText(rs.getString("discount"));
                tfppn.setText(rs.getString("ppn"));
                tfcust.setText(rs.getString("customer"));
                taheader.setText(rs.getString("header"));
                tafooter.setText(rs.getString("footer"));
                txtcust.setText(cari_customer(rs.getString("customer")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(offerform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private String cari_customer(String cust) {
        String sql = "select * from customer where id=?";
        String nama = null;
        try {
            PreparedStatement ps = conec.prepareStatement(sql);
            ps.setString(1, cust);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                nama = rs.getString("nama");
                return nama;
            }else{
                nama = cust;
                return nama;
            }
        } catch (SQLException ex) {
            Logger.getLogger(offerform.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(nama);
        return nama;
    }
    public void nomor_faktur() {
        String thn = txtDate.getText().substring(2, 4);
        String pre = "OF"+thn+"-SSM";
        String sql = "select * from faktur where faktur=?";
        try {
            PreparedStatement st = conec.prepareStatement(sql);
            st.setString(1, pre);
            ResultSet rs = st.executeQuery();
            if(rs.next()){
                int no = rs.getInt("no_faktur")+1;
                String pjg = String.valueOf(no);
                int a = pjg.length();
                if(a ==1 ){
                    tfnomor.setText(pre+"-000"+pjg);
                }else if(a==2){
                    tfnomor.setText(pre+"-00"+pjg);
                }else if(a==3){
                    tfnomor.setText(pre+"-0"+pjg);
                }else if(a==4){
                    tfnomor.setText(pre+"-"+pjg);
                }
            }else{
                PreparedStatement pd = conec.prepareStatement("insert into faktur (faktur, no_faktur) values('"+pre+"','0')");
                pd.executeUpdate();
                tfnomor.setText(pre+"-0001");
            }
            System.out.println(tfnomor.getText().substring(0,tfnomor.getText().length()-5));
        } catch (SQLException ex) {
            Logger.getLogger(offerform.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public void update_faktur() {
        String sql = "update faktur set no_faktur=no_faktur+1 where faktur=?";
        try {
            PreparedStatement st = conec.prepareStatement(sql);
            st.setString(1, tfnomor.getText().substring(0,tfnomor.getText().length()-5));
            st.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(offerform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
