/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import koneksi.koneksi;

/**
 *
 * @author subki
 */
public class priceform extends javax.swing.JDialog {

    Connection conec;
    public priceform(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        this.setTitle("Data Material");
        this.setIconImage(new ImageIcon(getClass().getResource("/image/ssm.png")).getImage());
        conec = new koneksi().connection();
        tadeskrip.setLineWrap(true);
        tadeskrip.setWrapStyleWord(true);
        tfnama.setEnabled(false);
        tadeskrip.setEnabled(false);
        tfunit.setEnabled(false);
        jButton1.setIcon(new ImageIcon(getClass().getResource("/image/search110.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadeskrip = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfaktual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfjual = new javax.swing.JTextField();
        jPanel1 = new style.ImagePrice();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tfunit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Material");

        tfkode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfkodeKeyPressed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tadeskrip.setColumns(20);
        tadeskrip.setRows(5);
        jScrollPane1.setViewportView(tadeskrip);

        jLabel2.setText("Rp.");

        jLabel3.setText("Harga Aktual");

        tfaktual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfaktualKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfaktualKeyTyped(evt);
            }
        });

        jLabel4.setText("Harga Jual");

        jLabel5.setText("Rp.");

        tfjual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfjualKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfjualKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        btnSubmit.setText("jButton2");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfkode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(tfnama)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfjual))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfaktual, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfunit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(tfaktual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(tfjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSubmit)
                        .addComponent(btnCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfaktualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfaktualKeyReleased
        NumberFormat no = NumberFormat.getInstance();
        double nominal = Long.valueOf(tfaktual.getText().replace(",", "").replace(".", "").trim());
        no.setMaximumFractionDigits(3);
        tfaktual.setText(no.format(nominal));
    }//GEN-LAST:event_tfaktualKeyReleased

    private void tfaktualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfaktualKeyTyped
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))){
            evt.consume();
        }
    }//GEN-LAST:event_tfaktualKeyTyped

    private void tfjualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfjualKeyReleased
        NumberFormat no = NumberFormat.getInstance();
        double nominal = Long.valueOf(tfjual.getText().replace(",", "").replace(".", "").trim());
        no.setMaximumFractionDigits(3);
        tfjual.setText(no.format(nominal));
    }//GEN-LAST:event_tfjualKeyReleased

    private void tfjualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfjualKeyTyped
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))){
            evt.consume();
        }
    }//GEN-LAST:event_tfjualKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DetailView dt = new DetailView(null, true);
        dt.setVisible(true);
        DetailOBJ obj = dt.getData();
        if(obj != null){
            tfkode.setText(obj.getItemno());
            String no = tfkode.getText();
            search(no);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfkodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfkodeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            search(tfkode.getText());
        }
    }//GEN-LAST:event_tfkodeKeyPressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(btnSubmit.getText().equals("Save")){
            save();
        }
        if(btnSubmit.getText().equals("Update")){
            update();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(priceform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(priceform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(priceform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(priceform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                priceform dialog = new priceform(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tadeskrip;
    private javax.swing.JTextField tfaktual;
    private javax.swing.JTextField tfjual;
    private javax.swing.JTextField tfkode;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfunit;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JTextArea getTadeskrip() {
        return tadeskrip;
    }

    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public JTextField getTfunit() {
        return tfunit;
    }

    public JTextField getTfnama() {
        return tfnama;
    }

    public JTextField getTfkode() {
        return tfkode;
    }

    public JTextField getTfaktual() {
        return tfaktual;
    }

    public JTextField getTfjual() {
        return tfjual;
    }

    private void search(String no) {
        String sql = "select * from component where item_no=?";
        try {
            PreparedStatement ps = conec.prepareStatement(sql);
            ps.setString(1, no);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                tfnama.setText(rs.getString("name"));
                tadeskrip.setText(rs.getString("description"));
                tfunit.setText(rs.getString("unit"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(priceform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void save() {
        String a = tfkode.getText();
        String b = tfaktual.getText().replace(",", "").replace(".", "");
        String c = tfjual.getText().replace(",", "").replace(".", "");
        if(!a.equals("")){
            String sql_cari = "select * from price where item_no=?";
            String sql_insert = "insert into price (item_no, act_price, deal_price) values (?,?,?)";
            
            try {
                PreparedStatement st = conec.prepareStatement(sql_cari);
                st.setString(1, a);
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Harga Material dengan Kode : "+a+" sudah ada. \n "
                            + " Harga Aktual : "+rs.getString("act_price")+" \n"
                            + " Harga Jual   : "+rs.getString("deal_price")+" \n Update Data?", 
                                  "Warning", 
                                  JOptionPane.YES_NO_OPTION); 
                    if (selectedOption == JOptionPane.YES_OPTION) { 
                        update();
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(priceform.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                PreparedStatement ps = conec.prepareStatement(sql_insert);
                ps.setString(1, a);
                ps.setString(2, b);
                ps.setString(3, c);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data berhasil di tambahkan");
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(priceform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Kode Material tidak boleh kosong");
        }
    }
    private void update(){
        String a = tfkode.getText();
        String b = tfaktual.getText().replace(",", "").replace(".", "");
        String c = tfjual.getText().replace(",", "").replace(".", "");
        if(!a.equals("")){
            String sql = "update price set act_price=?, deal_price=? where item_no=?";
            try {
                PreparedStatement ps = conec.prepareStatement(sql);
                ps.setString(1, b);
                ps.setString(2, c);
                ps.setString(3, a);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(priceform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Kode Material tidak boleh kosong");
        }
    }
}
